### ISSUE TITLE
Zabbix 2.4.5 failes while importing Templates

### ISSUE THREAD

**Issue by Stezii** [harryklein/zabbix-banana-pi#1]
Device: Banana Pro

zabbix_template_banana_pi_cpu.xml & zabbix_template_banana_pi_power_supply.xml
XML file contains fatal error 41:Specification mandate value for attribute data-pjax-transient [ Line: 32 | Column: 40 ]

**Comment by harryklein** [comment]
If you are looking for the described errors in the web, so there are many results. Example:
https://github.com/jjmartres/Zabbix/issues/13

Harry

**Comment by Stezii** [comment]
Copying the XML stuff manually to local XML documents (ANSI) did the trick.
